name: lint

on: push

env:
  PNPM_VERSION: '8'
  NODE_VERSION: '20.9'

jobs:
  check:
    strategy:
      fail-fast: true

    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
        id: install

      - name: Run linter
        run: pnpm run check
        id: lint
